[package]
name = "repgrep"
version = "0.16.1"
description = "An interactive command line replacer for `ripgrep`."
homepage = "https://github.com/acheronfail/repgrep"
repository = "https://github.com/acheronfail/repgrep"
keywords = ["find", "replace", "ripgrep", "regex", "grep"]
categories = ["command-line-utilities", "text-processing"]
authors = ["acheronfail <acheronfail@gmail.com>"]
license = "Unlicense OR MIT OR Apache-2.0"
edition = "2024"
rust-version = "1.96"
build = "build.rs"

[badges]
is-it-maintained-issue-resolution = { repository = "acheronfail/repgrep" }
is-it-maintained-open-issues = { repository = "acheronfail/repgrep" }

[[bin]]
name = "rgr"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.104"
base64-simd = { version = "0.8.0", features = ["detect"] }
chardet = "0.2.4"
const_format = "0.2.36"
crossterm = "0.29.0"
either = "1.18.0"
encoding = "0.2.33"
flexi_logger = "0.31.10"
grep-matcher = "0.1.9"
grep-pcre2 = "0.1.10"
grep-regex = "0.1.14"
lexopt = "0.3.2"
log = "0.4.34"
safe-transmute = "0.11.3"
serde = { version = "1.0.229", features = ["derive"] }
serde_derive = "1.0.229"
serde_json = "1.0.151"
tempfile = "3.27.0"
ratatui = { version = "0.30.2", default-features = false, features = ["crossterm"] }
unicode-width = "0.2.2"

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }
crossbeam-queue = "0.3.13"
hex = "0.4.3"
insta = "1.48.0"
memmap = "0.7.0"
num_cpus = "1.17.0"
paste = "1.0.15"
pretty_assertions = "1.4.1"
rayon = "1.12.0"

[profile.release]
# See: https://github.com/johnthagen/min-sized-rust
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true

[[bench]]
name = "parsing_json"
harness = false
