# Thanks goes to `BurntSushi/ripgrep` for the original template for GitHub Actions!

name: release
on:
  push:
    # Enable when testing release infrastructure on a branch.
    # branches:
    # - test-release
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
permissions:
  contents: read
jobs:
  # This job is responsible for _creating_ the GitHub release.
  # It passes the resolved version to the `build-release` jobs, which publish
  # the platform archives.
  #
  # This job runs only once, before the `build-release` jobs.
  create-release:
    name: create-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      version: ${{ steps.version.outputs.version }}
    # env:
    #   # Set to force version number, e.g., when no tag exists.
    #   CRATE_VERSION: TEST-0.0.0
    steps:
      - name: Get the release version from the tag
        id: version
        shell: bash
        run: |
          version="${CRATE_VERSION:-${GITHUB_REF#refs/tags/}}"
          echo "CRATE_VERSION=$version" >> "$GITHUB_ENV"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "$CRATE_VERSION" \
            --repo "$GITHUB_REPOSITORY" \
            --title "$CRATE_VERSION" \
            --draft

  # This job runs _after_ the `create-release` job and uploads its archives to that release.
  build-release:
    name: build-release
    needs: ['create-release']
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    env:
      # For some builds, we use cross to test on 32-bit and big-endian
      # systems.
      CARGO: cargo
      # When CARGO is set to CROSS, this is set to `--target matrix.target`.
      TARGET_FLAGS:
      # When CARGO is set to CROSS, TARGET_DIR includes matrix.target.
      TARGET_DIR: ./target
      # Emit backtraces on panics.
      RUST_BACKTRACE: 1
      RELEASE_VERSION: ${{ needs.create-release.outputs.version }}
    strategy:
      fail-fast: false
      matrix:
        build: [linux-gnu, linux-musl, linux-arm-gnueabihf, linux-aarch64-gnu, linux-aarch64-musl, macos, macos-aarch64, win-msvc, win-gnu, win32-msvc]
        include:
        # NOTE: we pin to a specific version since sometimes things fail to compile on the latest nightly builds
        - build: linux-gnu
          os: ubuntu-latest
          rust: nightly
          target: x86_64-unknown-linux-gnu
        - build: linux-musl
          os: ubuntu-latest
          rust: nightly
          target: x86_64-unknown-linux-musl
        - build: linux-arm-gnueabihf
          os: ubuntu-latest
          rust: nightly
          target: arm-unknown-linux-gnueabihf
        - build: linux-aarch64-gnu
          os: ubuntu-latest
          rust: nightly
          target: aarch64-unknown-linux-gnu
        - build: linux-aarch64-musl
          os: ubuntu-latest
          rust: nightly
          target: aarch64-unknown-linux-musl
        - build: macos
          os: macos-latest
          rust: nightly
          target: x86_64-apple-darwin
        - build: macos-aarch64
          os: macos-latest
          rust: nightly
          target: aarch64-apple-darwin
        - build: win-msvc
          os: windows-2022
          rust: nightly
          target: x86_64-pc-windows-msvc
        - build: win-gnu
          os: windows-2022
          rust: nightly-x86_64-gnu
          target: x86_64-pc-windows-gnu
        - build: win32-msvc
          os: windows-2022
          rust: nightly
          target: i686-pc-windows-msvc

    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install packages (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        ci/install-packages-ubuntu.sh

    - name: Install packages (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        ci/install-packages-macos.sh

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        target: ${{ matrix.target }}
        cache: false
        rustflags: ""

    # cache
    - uses: actions/cache@v6
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          target/
        key: ${{ runner.os }}-cargo-${{ matrix.target }}

    # We install ripgrep via cargo to get the latest version (we need at least 14)
    # since ubuntu is still on 13 (at least it is while this is being written...)
    # We need 14 in order to generate completion files.
    - name: Install ripgrep
      run: cargo install ripgrep

    - name: Use Cross
      run: |
        cargo install cross
        echo "CARGO=cross" >> $GITHUB_ENV
        echo "TARGET_FLAGS=--target ${{ matrix.target }}" >> $GITHUB_ENV
        echo "TARGET_DIR=./target/${{ matrix.target }}" >> $GITHUB_ENV

    - name: Show command used for Cargo
      run: |
        echo "cargo command is: ${{ env.CARGO }}"
        echo "target flag is: ${{ env.TARGET_FLAGS }}"
        echo "target dir is: ${{ env.TARGET_DIR }}"

    - name: Build release binary
      run: ${{ env.CARGO }} build --verbose --release ${{ env.TARGET_FLAGS }}
      timeout-minutes: 10

    - name: Strip release binary (linux and macos)
      if: matrix.target == 'x86_64-unknown-linux-gnu' || matrix.target == 'x86_64-apple-darwin' || matrix.target == 'aarch64-apple-darwin'
      run: strip "target/${{ matrix.target }}/release/rgr"

    - name: Strip release binary (cross)
      if: matrix.target == 'x86_64-unknown-linux-musl' || matrix.target == 'arm-unknown-linux-gnueabihf' || matrix.target == 'aarch64-unknown-linux-gnu' || matrix.target == 'aarch64-unknown-linux-musl'
      run: |
        case "${{ matrix.target }}" in
          x86_64-unknown-linux-musl) STRIP="x86_64-linux-musl-strip" ; IMAGE="ghcr.io/cross-rs/x86_64-unknown-linux-musl:main" ;;
          arm-unknown-linux-gnueabihf) STRIP="arm-unknown-linux-gnueabihf-strip" ; IMAGE="ghcr.io/cross-rs/arm-unknown-linux-gnueabihf:main" ;;
          aarch64-unknown-linux-gnu) STRIP="aarch64-linux-gnu-strip" ; IMAGE="ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main" ;;
          aarch64-unknown-linux-musl) STRIP="aarch64-linux-musl-strip" ; IMAGE="ghcr.io/cross-rs/aarch64-unknown-linux-musl:main" ;;
        esac
        docker run --rm -v "$PWD/target:/target:Z" "$IMAGE" "$STRIP" "/target/${{ matrix.target }}/release/rgr"

    # FIXME: for some reasons the manpage isn't generated in CI from the build.rs script.
    # So we build it (again?) here too.
    # NOTE: the windows builds don't create a target-triple directory under "target/"
    - name: Build archive
      shell: bash
      run: |
        outdir="$(ci/cargo-out-dir.sh "${{ env.TARGET_DIR }}")"
        if [ "${{ matrix.os }}" != "windows-2022" ]; then
          asciidoctor --doctype manpage --backend manpage --destination-dir "$outdir" doc/rgr.1.template
        fi
        staging="repgrep-${{ env.RELEASE_VERSION }}-${{ matrix.target }}"
        mkdir -p "$staging"/{complete,doc}

        echo 'complete -F _rg rgr'                              > "${outdir}/rgr.bash"
        echo 'compdef $_comps[rg] rgr'                          > "${outdir}/_rgr"
        rg --generate complete-fish | sed 's/-c rg/-c rgr/'     > "${outdir}/rgr.fish"
        rg --generate complete-powershell | sed "s/'rg'/'rgr'/" > "${outdir}/_rgr.ps1"

        cp {LICENSE-*,CHANGELOG.md,README.md} "$staging/doc/"
        cp "$outdir"/{_rgr,rgr.bash,rgr.fish,_rgr.ps1} "$staging/complete/"

        if [ "${{ matrix.os }}" = "windows-2022" ]; then
          cp "target/release/rgr.exe" "$staging/"
          7z a "$staging.zip" "$staging"
          echo "ASSET=$staging.zip" >> $GITHUB_ENV
        else
          cp "$outdir"/rgr.1 "$staging/doc/"
          cp "target/${{ matrix.target }}/release/rgr" "$staging/"
          tar czf "$staging.tar.gz" "$staging"
          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
        fi

    - name: Upload release archive
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh release upload "$RELEASE_VERSION" "$ASSET" \
          --repo "$GITHUB_REPOSITORY"


  # This job runs after all release archives have been built and uploaded.
  publish-crate:
    name: publish-crate
    needs: ['build-release']
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 1
        submodules: recursive

    - name: Install packages (Ubuntu)
      run: |
        ci/install-packages-ubuntu.sh

    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        override: true
        target: x86_64-unknown-linux-gnu
        cache: false
        rustflags: ""

    - name: Publish Crate
      shell: bash
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: |
        cargo publish
